use_frameworks!
generate_bridge_support!

workspace 'MirrorKit'
project 'iOS/MirrorKit-iOS.xcodeproj'
project 'macOS/MirrorKit-macOS.xcodeproj'

target :MirrorKit_iOS do
    platform :ios, '7.0'
    pod 'MirrorKit', :path => '../'
    project 'iOS/MirrorKit-iOS.xcodeproj'

    target 'MirrorKit_iOS_Tests' do
        inherit! :search_paths
    end
end

target :MirrorKit_macOS do
    platform :osx, '10.8'
    pod 'MirrorKit', :path => '../'
    project 'macOS/MirrorKit-macOS.xcodeproj'
end

